export const ongoingDebateTopics = [
  { "debateId": "1twpt", "debateTitle": "Should India adopt a two-party political system?" },
  { "debateId": "2resv", "debateTitle": "Is the reservation system still relevant in India?" },
  { "debateId": "3dmtn", "debateTitle": "Demonetization: Was it a success or a failure?" },
  { "debateId": "4crpto", "debateTitle": "Should the use of cryptocurrency be regulated in India?" },
  { "debateId": "5ucc", "debateTitle": "Is the Uniform Civil Code necessary for India?" },
  { "debateId": "6renen", "debateTitle": "Should India prioritize renewable energy over conventional sources?" },
  { "debateId": "7edusys", "debateTitle": "Is the education system in India effective in preparing students for the future?" },
  { "debateId": "8prmhd", "debateTitle": "Should the government promote Hindi as the primary language of communication?" },
  { "debateId": "9dthpt", "debateTitle": "Is the death penalty justified in heinous crimes?" },
  { "debateId": "10vot16", "debateTitle": "Should the voting age in India be lowered to 16?" },
  { "debateId": "11polre", "debateTitle": "Is there a need for police reforms in India?" },
  { "debateId": "12spexp", "debateTitle": "Should India focus more on space exploration or poverty alleviation?" },
  { "debateId": "13edures", "debateTitle": "Is the reservation policy in educational institutions fair?" },
  { "debateId": "14hlthdf", "debateTitle": "Should the government invest more in healthcare or defense?" },
  { "debateId": "15cultcens", "debateTitle": "Is censorship necessary for maintaining cultural and social harmony?" },
  { "debateId": "16iplprio", "debateTitle": "Should the Indian Premier League (IPL) be considered a priority over other sports?" },
  { "debateId": "17aadpvt", "debateTitle": "Is the Aadhaar system a threat to privacy?" },
  { "debateId": "18govveg", "debateTitle": "Should the government promote vegetarianism for environmental reasons?" },
  { "debateId": "19sclmediareg", "debateTitle": "Is there a need for stricter regulations on social media in India?" },
  { "debateId": "20healthcare", "debateTitle": "Should India invest more in traditional medicine or modern healthcare?" },
];
