export const ongoingDebateTopics = [
  { id: "1twpt", topicName: "Should India adopt a two-party political system?" },
  { id: "2resv", topicName: "Is the reservation system still relevant in India?" },
  { id: "3dmtn", topicName: "Demonetization: Was it a success or a failure?" },
  { id: "4crpto", topicName: "Should the use of cryptocurrency be regulated in India?" },
  { id: "5ucc", topicName: "Is the Uniform Civil Code necessary for India?" },
  { id: "6renen", topicName: "Should India prioritize renewable energy over conventional sources?" },
  { id: "7edusys", topicName: "Is the education system in India effective in preparing students for the future?" },
  { id: "8prmhd", topicName: "Should the government promote Hindi as the primary language of communication?" },
  { id: "9dthpt", topicName: "Is the death penalty justified in heinous crimes?" },
  { id: "10vot16", topicName: "Should the voting age in India be lowered to 16?" },
  { id: "11polre", topicName: "Is there a need for police reforms in India?" },
  { id: "12spexp", topicName: "Should India focus more on space exploration or poverty alleviation?" },
  { id: "13edures", topicName: "Is the reservation policy in educational institutions fair?" },
  { id: "14hlthdf", topicName: "Should the government invest more in healthcare or defense?" },
  { id: "15cultcens", topicName: "Is censorship necessary for maintaining cultural and social harmony?" },
  { id: "16iplprio", topicName: "Should the Indian Premier League (IPL) be considered a priority over other sports?" },
  { id: "17aadpvt", topicName: "Is the Aadhaar system a threat to privacy?" },
  { id: "18govveg", topicName: "Should the government promote vegetarianism for environmental reasons?" },
  { id: "19sclmediareg", topicName: "Is there a need for stricter regulations on social media in India?" },
  { id: "20healthcare", topicName: "Should India invest more in traditional medicine or modern healthcare?" },
];
