export const trendingData = [
    { text: 'Football World Cup 2023 kicks off' },
    { text: 'New breakthrough in AI technology announced' },
    { text: 'Stock market hits record high' },
    { text: 'SpaceX launches new satellite into orbit' },
    { text: 'Latest advancements in renewable energy' },
    { text: 'NBA Finals: Exciting Game 7 showdown' },
    { text: 'Apple unveils the latest iPhone model' },
    { text: 'Global economic summit addresses challenges' },
    { text: 'Formula 1 Grand Prix comes to an end' },
    { text: 'Google announces major software update' },
    { text: 'Top CEOs discuss future business trends' },
    { text: 'Virtual reality shaping the gaming industry' },
    { text: 'Cryptocurrency market experiences volatility' },
    { text: 'Major tech company acquires startup' },
    { text: 'Olympic Games 2024 host city revealed' },
  ];